### ISSUE TITLE
The healthcheck port should be configurable

### ISSUE THREAD

**Issue by OmegaVVeapon** [OmegaVVeapon/kopf-k8s-sidecar#27]
As said in title.

Users are utilizing the sidecar in setups outside the typical grafana setups we're accustomed to and those pods may already be using port `8080`.

We should allow that port to be set to something else by the user.

**Comment by gburton1** [comment]
Default to a less common port? Even with a config option, it will be a lift to propagate the configurability out to the charts where the sidecar is used like Grafana/Cortex, especially since the kiwigrid sidecar implementation doesn't expose this health check port option.

**Comment by OmegaVVeapon** [comment]
That's a fair point.
The kiwigrid implementation doesn't have a healthcheck endpoint to begin with.
Until I can get those PRs approved, that seems a sensible choice.
Do you have a preference? I was thinking about `8181`.

**Comment by gburton1** [comment]
8181 looks good to me.

**Comment by OmegaVVeapon** [comment]
Things look good on my end, think you could try image `omegavveapon/kopf-k8s-sidecar:configurable-healthcheck-port` on your side @gburton1 before I merge that PR?

Edit: Nvm, saw your approval. Proceeding with the merge. Thanks!
